version: '3.7'
services:
    nginx:
        image: fruits-detector/nginx-rtmp
        build:
            context: ./nginx-rtmp
        ports:
            - 1935:1935
            - 8080:80
    api:
        image: fruits-detector/api
        build:
            context: ./api
        ports:
            - 5000:5000
    detector:
        image: fruits-detector/detector
        build:
            context: ./detector
        volumes:
           - ./detector/input:/usr/src/app/input
    front:
        image: fruits-detector/front
        build:
            context: ./front
        ports:
            - 80:8080
    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
    rabbitmq:
        image: rabbitmq:3-management
        restart: always
        ports:
            - 15672:15672
