version: '3.7'
services:
    nginx:
        image: tiangolo/nginx-rtmp
        ports:
            - 1935:1935
    train:
        image: train
        build:
          context: ./
          dockerfile: ./docker/TrainDockerfile
